import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import Footer from '@/app/components/nav/Footer';
import { Toaster } from '@/app/components/ui/toaster';
import { ThemeProvider } from '@/app/components/theme-provider';
import Hydration from '../hydration';
import Navbar from '@/app/components/nav/Navbar';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
});
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export default function RootLayout({
  children,
  modal
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <div>
      <Hydration />
      <ThemeProvider
        attribute='class'
        defaultTheme='system'
        enableSystem
        disableTransitionOnChange
      >
        <Navbar />
        {children}
        {modal}
        <Footer />
        <Toaster />
      </ThemeProvider>
    </div>
  );
}
