# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Package

on:
  push:
    tags: ['releases-**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master
        with:
          ref: main

      - name: Generate Environment Variables File for Production
        run: |
          echo "NEXT_PUBLIC_KAKAO_MAP_CLIENT=$NEXT_PUBLIC_KAKAO_MAP_CLIENT" >> .env.production
          echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env.production
          echo "NEXT_PUBLIC_REST_API_KEY=$NEXT_PUBLIC_REST_API_KEY" >> .env.production
        env:
          NEXT_PUBLIC_KAKAO_MAP_CLIENT: ${{ secrets.NEXT_PUBLIC_KAKAO_MAP_CLIENT }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_REST_API_KEY: ${{ secrets.NEXT_PUBLIC_REST_API_KEY }}

      - name: Install Dependencies
        run: |
          yarn

      - name: Build
        run: |
          yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: JejuFront
          path: ${{ github.workspace }}/jejufront/front

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: JejuFront
          path: ${{ github.workspace }}/jejufront/front

      - name: SCP transfer
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          host: ${{ secrets.SSH_SERVER_IP }}
          port: ${{ secrets.SSH_PORT }}
          rm: true
          source: ${{ github.workspace }}/jejufront/front
          target: ./jeju_front/
          strip_components: 1
